### ISSUE TITLE
Command create-graphless not working

### ISSUE THREAD

**Issue by rokkanen** [simonaco/create-graphless#1]
Hello,

I follow the 3 steps of documentation:

1/ I run : create-graphless --git --install or just create-graphless
2/ I obtain db or Javascript choise
3/ I choose an option (db or Javascript)
4/ when I validate, I get this
ERROR Invalid template name

My environnement:
Windows 10 1903
NodeJS v11.12.0

**Comment by fidoogle** [comment]
I do the same thing and get the same ERROR Invalid template name. This happens when I choose Javascript and hit ENTER.

**Comment by markstijnman** [comment]
Same problem here, seems to be a Windows issue. The `new URL(currentFileUrl).pathname` returns something like `"/C:/Users/<USERNAME>/AppData/Roaming/npm/node_modules/@simonaco/create-graphless/src/main.js"`. `path.resolve` then mangles this to "C:\C:\Users\..." which obviously won't work. I could make it work by replacing `new URL(currentFileUrl).pathname` with  `fileURLToPath(currentFileUrl)`.

**Comment by SameerDoshi** [comment]
This was solved by the last PR.  Have fun all!

**Comment by simonaco** [comment]
thanks @SameerDoshi
